apiVersion: v1
kind: Pod
metadata:
  name: pod-annotations
  labels:
    app: web
    env: dev
    tier: backend
  annotations: 
    description: "this is a web application@google.com"
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alma-linux-container
    image: alma-linux:latest
    command: ["sleep", "infinity"]